import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { readFile } from "node:fs/promises";
import path from "node:path";

export type QuotePdfData = {
  quoteNumber: string;
  status: string;
  customerName: string;
  customerPhone: string | null;
  customerEmail: string | null;
  carLabel: string;
  startDate: string;
  endDate: string;
  dailyRate: number;
  totalPrice: number;
  notes: string | null;
};

export async function buildQuotePdf(data: QuotePdfData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const marginX = 48;
  let y = 792;

  try {
    const logoPath = path.join(process.cwd(), "public", "yarutso-logo.png");
    const logoBytes = await readFile(logoPath);
    const logo = await pdfDoc.embedPng(logoBytes);
    const logoW = 145;
    const logoH = (logo.height / logo.width) * logoW;
    page.drawImage(logo, { x: marginX, y: y - logoH, width: logoW, height: logoH });
  } catch {
    // If logo file is missing in any environment, continue without failing PDF generation.
  }

  page.drawText("Quotation", {
    x: marginX + 160,
    y: y - 14,
    size: 22,
    font: fontBold,
    color: rgb(0.12, 0.27, 0.75),
  });

  y -= 70;

  const tableX = marginX;
  const tableW = 500;
  const rowH = 28;
  const leftColW = 170;
  const rows: Array<[string, string]> = [
    ["Quote Number", data.quoteNumber],
    ["Customer", data.customerName],
    ["Phone", data.customerPhone ?? "-"],
    ["Email", data.customerEmail ?? "-"],
    ["Vehicle", data.carLabel],
    ["Start Date", data.startDate],
    ["End Date", data.endDate],
    ["Daily Rate", `$${data.dailyRate.toFixed(2)}`],
    ["Total Amount", `$${data.totalPrice.toFixed(2)}`],
  ];

  page.drawRectangle({
    x: tableX,
    y: y - rowH,
    width: tableW,
    height: rowH,
    color: rgb(0.92, 0.95, 1),
    borderWidth: 1,
    borderColor: rgb(0.75, 0.8, 0.9),
  });
  page.drawText("Field", {
    x: tableX + 8,
    y: y - 18,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.2, 0.3),
  });
  page.drawText("Value", {
    x: tableX + leftColW + 8,
    y: y - 18,
    size: 11,
    font: fontBold,
    color: rgb(0.15, 0.2, 0.3),
  });
  y -= rowH;

  for (const [label, value] of rows) {
    page.drawRectangle({
      x: tableX,
      y: y - rowH,
      width: tableW,
      height: rowH,
      borderWidth: 1,
      borderColor: rgb(0.85, 0.88, 0.93),
      color: rgb(1, 1, 1),
    });
    page.drawLine({
      start: { x: tableX + leftColW, y: y - rowH },
      end: { x: tableX + leftColW, y },
      thickness: 1,
      color: rgb(0.87, 0.9, 0.95),
    });
    page.drawText(label, {
      x: tableX + 8,
      y: y - 18,
      size: 10.5,
      font: fontBold,
      color: rgb(0.17, 0.17, 0.17),
    });
    page.drawText(value, {
      x: tableX + leftColW + 8,
      y: y - 18,
      size: 10.5,
      font,
      color: rgb(0.23, 0.23, 0.23),
      maxWidth: tableW - leftColW - 16,
    });
    y -= rowH;
  }

  y -= 18;
  page.drawText("Notes", {
    x: marginX,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.12, 0.12, 0.12),
  });
  y -= 18;
  page.drawText(data.notes || "-", {
    x: marginX,
    y,
    size: 11,
    font,
    color: rgb(0.2, 0.2, 0.2),
    maxWidth: 500,
    lineHeight: 14,
  });

  y -= 80;
  page.drawText("Generated by Yarutso Car Rental System", {
    x: marginX,
    y,
    size: 10,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  return pdfDoc.save();
}

