import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export type QuotePdfData = {
  quoteNumber: string;
  status: string;
  customerName: string;
  customerPhone: string | null;
  customerEmail: string | null;
  carLabel: string;
  startDate: string;
  endDate: string;
  dailyRate: number;
  totalPrice: number;
  notes: string | null;
};

export async function buildQuotePdf(data: QuotePdfData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const marginX = 48;
  let y = 790;

  const drawLine = (label: string, value: string) => {
    page.drawText(label, { x: marginX, y, size: 11, font: fontBold, color: rgb(0.12, 0.12, 0.12) });
    page.drawText(value, { x: marginX + 160, y, size: 11, font, color: rgb(0.2, 0.2, 0.2) });
    y -= 20;
  };

  page.drawText("Yarutso Car Rental", {
    x: marginX,
    y,
    size: 24,
    font: fontBold,
    color: rgb(0.2, 0.1, 0.55),
  });
  y -= 34;
  page.drawText("Quotation", {
    x: marginX,
    y,
    size: 16,
    font: fontBold,
    color: rgb(0.88, 0.14, 0.32),
  });
  y -= 30;

  drawLine("Quote Number", data.quoteNumber);
  drawLine("Status", data.status);
  drawLine("Customer", data.customerName);
  drawLine("Phone", data.customerPhone ?? "-");
  drawLine("Email", data.customerEmail ?? "-");
  drawLine("Car", data.carLabel);
  drawLine("Start Date", data.startDate);
  drawLine("End Date", data.endDate);
  drawLine("Daily Rate", `$${data.dailyRate.toFixed(2)}`);
  drawLine("Total Amount", `$${data.totalPrice.toFixed(2)}`);

  y -= 8;
  page.drawText("Notes", {
    x: marginX,
    y,
    size: 11,
    font: fontBold,
    color: rgb(0.12, 0.12, 0.12),
  });
  y -= 18;
  page.drawText(data.notes || "-", {
    x: marginX,
    y,
    size: 11,
    font,
    color: rgb(0.2, 0.2, 0.2),
    maxWidth: 500,
    lineHeight: 14,
  });

  y -= 120;
  page.drawText("Generated by Yarutso Car Rental System", {
    x: marginX,
    y,
    size: 10,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  return pdfDoc.save();
}

